### ISSUE TITLE
support writing junit-xml from jasmine-ci

### ISSUE THREAD

**Issue by dwt** [jasmine/jasmine-py#38]
Hi there,

I would like to run jasmine tests on a build server, but it seems there is no way to do this while getting output in the unit-xml format (that virtually all build servers can swallow).

Some solutions I would consider good:
* have a switch to deliver junit-xml instead of the current output.
* have some support for native junit-xml reporters in the configuration.yml file (e.g. via https://github.com/larrymyers/jasmine-reporters)
* have a switch that allows customizing the boot.js file to allow us to do this ourselves

**Comment by dwt** [comment]
ping @maintainers: any word on this? It would make the jasmine-ci commands really useful.

**Comment by slackersoft** [comment]
Including something like jasmine-reporters gets a bit tricky when the tests are being run in a full browser via selenium (as opposed to phantomjs), because the browser won't let you write to the local filesystem. Ultimately, I'd like to get this package to the same kind of point that the ruby gem is where a `Formatter` has a defined interface that we expect, which should make it easier to add a custom one for junit-xml or other things. For now, since we only have one formatter, I would be happy to review a pull request that adds a flag to `jasmine-ci` to add a junit-xml output file.

**Comment by dwt** [comment]
If you already use selenium to run the tests in a full browser, is there a specific reason you  don't extract the generated junit xml file via selenium too? That should work with all browsers automutable via selenium. PhantomJS already has API to interact with it, so that shouldn't be a problem too.

As for the formatters - another option would be to just allow junit.xml as an additional format, would you use that?

**Comment by slackersoft** [comment]
Selenium can only send back so much data from the browser, and since XML is fairly verbose, we will quickly run into issues with serializing all of the data back. Additionally, this would require Jasmine-Py to know details about how the Jasmine-Reporters save off the XML file inside the browser (which I doubt they really do).

For now, I think we want to just add an option to the `jasmine-ci` command to allow it to output a junit-xml file in addition to the normal CLI output.

**Comment by dwt** [comment]
Not sure if I have the time to cobble something together, but I think this bug report could be a nice reminder that this is wanted if I don't get to it. Or are you willing to put some time into this?

**Comment by sgravrock** [comment]
Closing since jasmine-py is deprecated and we don't intend to add any new features.
