### ISSUE TITLE
jasmine-ci: support command line arguments to the target browser

### ISSUE THREAD

**Issue by dwt** [jasmine/jasmine-py#39]
Today while trying to debug a problem with phantomjs I was really hoping for a way to tell it to enable remote debugging.

Sadly seems to not be possible.

Looking at the source, supporting an environment variable to provide `service_args` [here](https://github.com/jasmine/jasmine-py/blob/master/jasmine/ci.py#L102) seems like a relatively simple solution.

**Comment by slackersoft** [comment]
In order to support custom arguments to the underlying `WebDriver` that Jasmine is using, we would probably need a way for the user to provide a fully configured `WebDriver` object. The different browsers all have different `WebDriver` constructors with different arguments, so since we're using `__import__` to find the right browser, we can't really know which arguments it accepts for customization.

I would be happy to review a pull request that allowed a suite to provide the `WebDriver` fully constructed while using the existing code by default.

Thanks for using Jasmine!

**Comment by sgravrock** [comment]
Closing since jasmine-py is deprecated and we don't intend to add any new features.
